### ISSUE TITLE
Origin trial for embedders

### ISSUE THREAD

**Issue by bvattikonda** [abeyad/user-agent-reduction#2]
Is there a mechanism for embedders to enroll in the origin trial?

```
To get the reduced User-Agent request header, enroll the top-level sites in the origin trial and set the permissions policy to allow the client hints and the reduced User-Agent request header to propagate to the cross-origin requests.
```

indicates that as an embedder, we need all our partners to enroll in the origin trial for us to evaluate the impact of UA reduction which seems challenging.

**Comment by abeyad** [comment]
Hi Bhanu,

Currently, embedders can enroll in the origin trial and get a third-party origin trial token, which will allow them to get the reduced UA string in the Javascript APIs (`navigator.userAgent`, etc).  However, as you quoted, this will not enable the embedders to include the reduced UA string in the `User-Agent` request header, unless the top-level sites have enrolled in the origin trial.  We are working on a plan to overcome this shortcoming and hope to launch it in M96.  The plan would allow third-party embeds to send the reduced User-Agent header through a feature flag, without needing the top-level site to be enrolled in the origin trial; however this plan would *not* be in the form of an origin trial due to current origin trial infrastructure limitations.

We'll communicate when the experiment feature is available for third-party embeds to send the reduced UA request header.

**Comment by bvattikonda** [comment]
When available, how long do you expect to run the origin trial?

Do you expect the origin trial to finish before the UA reduction begins with minor version removal or do you see these happening in parallel?

**Comment by miketaylr** [comment]
The OT should run as long as the current 1P OT (more precisely, both should expire at the same time - [when Chrome 101 is released](https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html)).

If we get feedback that it's useful to keep running these OTs even after minor version has been removed, we can certainly ask Blink API owners ask for an extension.

**Comment by miketaylr** [comment]
Closing, as I think both questions have been answered. Please let me know if there's something I'm missing.
