### ISSUE TITLE
Application for User-Agent Reduction deprecation trial

### ISSUE THREAD

**Issue by KTetsuyuki** [abeyad/user-agent-reduction#8]
Do I have to register for the User-Agent Reduction deprecation trial by March 31?
If I register after April 1, can I still participate?

**Comment by abeyad** [comment]
You can register for the deprecation trial any time while the trial is valid.  This will be a longer-than-normal trial (going up until Chrome 113) due to the nature of the change and allowing the ecosystem to adapt.

Hopefully this answers your question but if it doesn't, please feel free to re-open.  Thanks!
